version: '3'
services:
  db:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: CourseDetail
    ports:
      - '3307:3306'
    networks:
      - custom-network
  backend:
    image: vishnuve/backend:fs
    container_name: 
      - spring-be
    restart: on-failure
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - custom-network
  frontend:
    image: vishnuve/frontend:fs-build
    container_name: react-fe
    ports:
      - '3000:3000'
    networks:
      - custom-network
    environment:
      - REACT_APP_API_URL=http://backend:8080/api
networks:
  custom-network:
    driver: bridge
