name: Build Docker Image

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        if [ -n "$(git diff --name-only ${{ github.sha }} ${{ github.sha^ }} 'frontend/')" ]; then
          # Build and push frontend Docker image
          cd frontend
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t vishnuve/frontend:latest .
          docker push vishnuve/frontend:latest
        fi

        if [ -n "$(git diff --name-only ${{ github.sha }} ${{ github.sha^ }} 'backend/')" ]; then
          # Build and push backend Docker image
          cd backend
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t vishnuve/backend:latest .
          docker push vishnuve/backend:latest
        fi
